### ISSUE TITLE
Dropdown list missing for search result page

### ISSUE THREAD

**Issue by vinoroidski** [hochschule-darmstadt/openartbrowser#559] opened 2021-06-30 19:03 UTC
**Describe the bug**
The search result page should have a dropdown list for selection between tabs (as used for the mobile view on all other pages).

**To Reproduce**
1. Go to 'openartbrowser' in mobile view (use chrome inspection tools).
2. Enter a term in the search bar and perform a search
4. See error (no dropdown list for tabs, just a list of all of them)

**Expected behavior**
A dropdown list should be provided on the search result page in mobile view instead of a list of all items. The default entry should be the "All" tab.

**Screenshots**
![3](https://user-images.githubusercontent.com/6040299/124017072-9165b780-d9e6-11eb-8bb9-be6a790cf2bd.PNG)

**Comment by EeveesEyes** [comment] 2021-06-30 19:51
Is this a duplicate of #549?

**Closed** 2021-07-01 09:46 UTC
Labels: User Interface, bug, duplicate, high priority, mobile
