### ISSUE TITLE
Timelines are sometimes not well scaled 

### ISSUE THREAD

**Issue by jschurse** [hochschule-darmstadt/openartbrowser#374] opened 2020-06-01 11:35 UTC
**Describe the bug**
On some pages e.g. https://cai-artbrowserstaging.fbi.h-da.de/de/movement/Q37853
The timelines aren't well scaled. A (maybe) wrongly dated artwork distortes the whole timeline so major parts of it are useless.

**To Reproduce**
Open a page in the artbrowser where some entries are statistical outliers

**Expected behavior**
statistical outliers are being ignored (?)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/12964877/83405215-51f82080-a40c-11ea-95d8-ed47479da22c.png)

**Comment by BernhardHumm** [comment] 2020-06-02 08:07
Wouldn’t it be better to correct the outliers in Wikidata?

 

 

 

------------------------------------

 

Von: jschurse [mailto:notifications@github.com] 
Gesendet: Montag, 1. Juni 2020 13:36
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/openartbrowser] Timelines are sometimes not well scaled (#374)

 

Describe the bug
On some pages e.g. https://cai-artbrowserstaging.fbi.h-da.de/de/movement/Q37853
The timelines aren't well scaled. A (maybe) wrongly dated artwork distortes the whole timeline so major parts of it are useless.

To Reproduce
Open a page in the artbrowser where some entries are statistical outliers

Expected behavior
statistical outliers are being ignored (?)

Screenshots
 <https://user-images.githubusercontent.com/12964877/83405215-51f82080-a40c-11ea-95d8-ed47479da22c.png>

**Comment by EeveesEyes** [comment] 2020-06-11 09:29
Actually this is a way bigger problem, because the 'sleeping hermaphroditus' is a ancient sculpture from 150 which was placed on a baroque mattress by bernini in year 1620. I don't see a easy fix for this problem at the moment.

**Comment by BernhardHumm** [comment] 2020-06-11 20:15
Ignore artworks with inception outside the start and end date of the movement.

 

Alternative: use a blacklist

 

 

------------------------------------

 

 

Von: Adrian Kailus [mailto:notifications@github.com] 
Gesendet: Donnerstag, 11. Juni 2020 11:30
An: hochschule-darmstadt/openartbrowser <openartbrowser@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/openartbrowser] Timelines are sometimes not well scaled (#374)

 

Actually this is a way bigger problem, because the 'sleeping hermaphroditus' is a ancient sculpture from 150 which was placed on a baroque mattress by bernini in year 1620. I don't see a easy fix for this problem at the moment.

**Closed** 2020-06-24 21:45 UTC
Labels: medium priority, usability improvement
