### ISSUE TITLE
Console error when opening pictures in full screen

### ISSUE THREAD

**Issue by tilomi** [hochschule-darmstadt/openartbrowser#54] opened 2019-11-18 16:39 UTC
When opening a picture in fullscreen on chrome this error is thrown in the console:
```stacktrace
pages-artwork-artwork-routing-module.js:478 Uncaught (in promise) TypeError: Document not active
    at exit (pages-artwork-artwork-routing-module.js:478)
    at ToggleFullscreenDirective.push../node_modules/ngx-image-viewer/ngx-image-viewer.es5.js.ToggleFullscreenDirective.ngOnChanges (pages-artwork-artwork-routing-module.js:308)
    at checkAndUpdateDirectiveInline (vendor.js:58218)
    at checkAndUpdateNodeInline (vendor.js:59486)
    at checkAndUpdateNode (vendor.js:59448)
    at debugCheckAndUpdateNode (vendor.js:60082)
    at debugCheckDirectivesFn (vendor.js:60042)
    at Object.eval [as updateDirectives] (ImageViewerComponent.html:2)
    at Object.debugUpdateDirectives [as updateDirectives] (vendor.js:60034)
    at checkAndUpdateView (vendor.js:59430)
```
On firefox i get the following error:
```stacktrace
TypeError: The expression cannot be converted to return the specified type.
```

**Comment by jschurse** [comment] 2019-11-18 21:49
This is a bug in the library used to display images:
https://www.npmjs.com/package/ngx-image-viewer
It can also be observed on the demo page of the lib here: 
https://angular-2wrbwp.stackblitz.io/

This issue is being discussed here:
https://github.com/jpilfold/ngx-image-viewer/issues/23

**Comment by jschurse** [comment] 2019-11-18 22:51
Since the package seems no longer to be maintained (there are already pull requests to fix this bug, which won't be merged) we have two options.
We can either override the packages dependencies to make it use a newer version of the screenfull package which no longer has this bug or use a different library.
Package overriding in npm is possible using the [npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) feature. But this only works if you´re doing a `npm i` without already having a node_modules dir. If you execute the command again it will override your overrides rendering this feature effectively useless.

**Comment by jschurse** [comment] 2019-11-21 12:01
We could fork this library, fix the issue ourself (update the screenfull dependency) and install the package from our github repository as described here:
https://docs.npmjs.com/cli/install

**Comment by JamieArmstrongArndt** [comment] 2019-12-01 13:22
Hey,
so I had a look at the described issue and it seems to be pretty straight forward. I would choose the way @jschurse described, of forking  [ngx-image-viewer](https://github.com/jpilfold/ngx-image-viewer) to our [hochschule-darmstadt organization account](https://github.com/hochschule-darmstadt) and implement the fix there. I would then add the package by using **npm install hochschule-darmstadt/ngx-image-viewer --save** and remove the old dependency. That should do the trick or are there any objections?

**Comment by jschurse** [comment] 2019-12-01 17:11
I'm looking forward to your PR :+1:

**Comment by JamieArmstrongArndt** [comment] 2019-12-01 20:48
Actually I noticed that the problem is not the ngx-image-viewer, but rather the dependency package [screenful](https://github.com/sindresorhus/screenfull.js/) used by the ngx-image-viewer. Is it possible to fork the repository, do the fix there and add the **fixed** screenfull to our dependencies?

**Comment by jschurse** [comment] 2019-12-01 22:39
> We can either override the packages dependencies to make it use a newer version of the screenfull package which no longer has this bug or use a different library.

As stated above the fix is to update the screenfull dependency. This has to be done in the ngx-image-viewer´s [package.json](https://github.com/jpilfold/ngx-image-viewer/blob/6ccf522e9386ee6f97a09b7d5c768b31d16dd07d/package.json#L59)

**Comment by JamieArmstrongArndt** [comment] 2019-12-04 21:30
Hey @jschurse ,
so I noticed that the problem is not really the screenfull package, but the fact that it was not correctly used in the ngx-image-viewer. Therefore I had just tried to fix the ngx-image-viewer library by adding the suggested fixes in the forum. But the by npm installed ngx-image-viewer dependency is in fact the dist file which is created with [packagr](https://www.npmjs.com/package/ng-packagr). I thought about adding the dependendy locally in a libs folder and referring it as "ngx-image-viewer": "file:./libs/ngx-image-viewer" in the package.json. What do you think about that solution?

**Comment by JamieArmstrongArndt** [comment] 2019-12-04 21:45
Thinking about it, putting it on another branch / own repository and install it would be much more convenient:
**"ngx-image-viewer": "github:hochschule-darmstadt/ngx-image-viewer#build"** 
or 
**ngx-image-viewer": "github:hochschule-darmstadt/ngx-image-viewer--build"**

**Comment by jschurse** [comment] 2019-12-11 21:10
Has been fixed!

**Closed by jschurse** 2019-12-11 21:10 UTC
Labels: bug, production server, staging server
